name: Build UIBase

on:
  push:
    branches: [ dev/gh-workflow-tests ]
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

#env:
#  VCPKG_BINARY_SOURCES: clear;x-azblob,${{ vars.AZ_BLOB_VCPKG_URL }},${{ secrets.AZ_BLOB_SAS }},readwrite

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install updates
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install build dependencies
        run: |
          sudo apt-get install -y \
          build-essential cmake curl git ninja-build pkg-config sudo tar unzip wget zip

      - name: Restore GCC
        id: cache-gcc-restore
        uses: actions/cache/restore@v4
        with:
          path: /opt/gcc-15
          key: gcc-15.2

      - name: Build and install GCC 15.2
        if: steps.cache-gcc-15_2.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y make gawk flex bison libgmp-dev libmpfr-dev libmpc-dev python3 binutils perl libisl-dev libzstd-dev gzip bzip2
          mkdir gcc-15
          cd gcc-15
          git clone https://gcc.gnu.org/git/gcc.git -b releases/gcc-15.2.0 --depth 1 gcc-15-source
          cd gcc-15-source
          ./contrib/download_prerequisites
          cd ..
          mkdir build
          cd build
          ../gcc-15-source/configure --prefix=/opt/gcc-15 --disable-multilib --enable-languages=c,c++
          make -j$(nproc)
          sudo make install

      - name: Save GCC
        id: cache-gcc-save
        if: always() && steps.cache-gcc-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-gcc-restore.outputs.cache-primary-key }}
          path: |
            /opt/gcc-15

      - name: Set GCC 15.2 as default
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /opt/gcc-15/bin/gcc 100
          sudo update-alternatives --install /usr/bin/g++ g++ /opt/gcc-15/bin/g++ 100

      - name: Configure UIBase
        id: configure-uibase
        uses: Kaedras/build-with-mob-action@master
        with:
          # skip build because we are going to build both Debug and RelWithDebInfo here
          mo2-skip-build: true
          mo2-owner: Kaedras
          mo2-branch: master

      # build both Debug and RelWithDebInfo for package
      - name: Build UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          cmake --build build --config Debug --target uibase-tests --verbose
          cmake --build build --config RelWithDebInfo --target uibase-tests --verbose

      - name: Test UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          ctest --test-dir build -C Debug --output-on-failure
          ctest --test-dir build -C RelWithDebInfo --output-on-failure

      - name: Install UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          cmake --install build --config Debug
          cmake --install build --config RelWithDebInfo

      # this tests that UI Base can be properly used as a CMake package
      - name: Test UI Base package
        run: |
          cmake -B build_tests . "-DCMAKE_PREFIX_PATH=$QT_ROOT_DIR;${{ github.workspace }}/install/lib/cmake/"
          cmake --build build_tests --config Debug
          cmake --build build_tests --config Release
          cmake --build build_tests --config RelWithDebInfo
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}/tests/cmake

      - name: Upload UI Base artifact
        uses: actions/upload-artifact@master
        with:
          name: uibase
          path: ./install

  publish:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: uibase
          path: ./install

      - name: Create UI Base archives
        run: |
          7z a uibase_${{ github.ref_name }}.7z ./install/*

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft=false --notes="${{ github.ref_name }}" "${{ github.ref_name }}" ./uibase_${{ github.ref_name }}.7z
