name: Build UIBase

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

#env:
#  VCPKG_BINARY_SOURCES: clear;x-azblob,${{ vars.AZ_BLOB_VCPKG_URL }},${{ secrets.AZ_BLOB_SAS }},readwrite

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
        include:
          - os: windows-2022
            build_dir: vsbuild
            prefix_path: "${env:QT_ROOT_DIR}\\msvc2022_64;"
            os_name: windows
          - os: ubuntu-24.04
            build_dir: build
            prefix_path: "$QT_ROOT_DIR;"
            os_name: linux

    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ runner.os == 'Linux' }}
        # upgrade from 24.04 (noble) to 25.10 (questing) because
        # old ubuntu versions cause errors
        name: Upgrade release to 25.10 (questing)
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
          sudo apt-get install update-manager-core -y
          sudo sed -i 's/lts/normal/g' /etc/update-manager/release-upgrades
          sudo sed -i 's/noble/questing/g' /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y -o "Dpkg::Options::=--force-confold"

      - if: ${{ runner.os == 'Linux' }}
        name: Install build dependencies
        run: |
          sudo apt-get install -y \
          build-essential cmake curl git ninja-build pkg-config tar unzip zip

      - name: Configure UIBase
        id: configure-uibase
        uses: Kaedras/build-with-mob-action@master
        with:
          # skip build because we are going to build both Debug and RelWithDebInfo here
          mo2-skip-build: true
          mo2-owner: Kaedras

      # build both Debug and RelWithDebInfo for package
      - name: Build UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          cmake --build ${{ matrix.build_dir }} --config Debug --target uibase-tests --verbose
          cmake --build ${{ matrix.build_dir }} --config RelWithDebInfo --target uibase-tests --verbose

      - name: Test UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          ctest --test-dir ${{ matrix.build_dir }} -C Debug --output-on-failure
          ctest --test-dir ${{ matrix.build_dir }} -C RelWithDebInfo --output-on-failure

      - name: Install UI Base
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}
        run: |
          cmake --install ${{ matrix.build_dir }} --config Debug
          cmake --install ${{ matrix.build_dir }} --config RelWithDebInfo

      # this tests that UI Base can be properly used as a CMake package
      - name: Test UI Base package
        run: |
          cmake -B build_tests . "-DCMAKE_PREFIX_PATH=${{ matrix.prefix_path }}${{ github.workspace }}/install/lib/cmake/"
          cmake --build build_tests --config Debug
          cmake --build build_tests --config Release
          cmake --build build_tests --config RelWithDebInfo
        working-directory: ${{ steps.configure-uibase.outputs.working-directory }}/tests/cmake

      - name: Upload UI Base artifact
        uses: actions/upload-artifact@master
        with:
          name: uibase_${{ matrix.os_name }}
          path: ./install

  publish:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@master
        with:
          name: uibase_windows
          path: ./install_windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@master
        with:
          name: uibase_linux
          path: ./install_linux

      - name: Create UI Base archives
        run: |
          7z a uibase_${{ github.ref_name }}_windows.7z ./install_windows/*
          7z a uibase_${{ github.ref_name }}_linux.7z ./install_linux/*

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft=false --notes="${{ github.ref_name }}" "${{ github.ref_name }}" ./uibase_${{ github.ref_name }}_windows.7z ./uibase_${{ github.ref_name }}_linux.7z
